left_shoulder_tilt_controller:
    id: 24
    base_length: 9.9
    extent: 4.0
    type: "pr2lite.actuator.linactdynamixel"

right_shoulder_tilt_controller:
    id: 25
    base_length: 9.9
    extent: 4.0
    type: "pr2lite.actuator.linactdynamixel"

