<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#slider"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">

  <include filename="$(find velo_description)/urdf/velo_v0/velo.gazebo.xacro" />
  <include filename="$(find velo_description)/urdf/velo_v0/velo.transmission.xacro" />

  <property name="M_PI" value="3.1415926535897931" />

  <property name="gripper_max_angle" value="1.4224433403753787" />

  <property name="finger_damping"             value="0.02" />
  <property name="gripper_damping"            value="10.0" />
  <property name="finger_tip_damping"         value="0.001" />

  <property name="finger_joint_effort_limit"  value="1000.0" />

  <property name="lcg_finger_to_finger_tip_x"     value="0.00" /> <!-- "0.050" -->
  <property name="lcg_palm_to_finger_x"           value="0.0587955" />
  <property name="lcg_palm_origin_offset"         value="0.053" />



  <xacro:macro name="pr2_lcgripper_v0" params="side reflect parent *origin">

    <link name="${side}_gripper_palm_link">
      <visual>
        <geometry>
          <mesh filename="package://velo_description/meshes/velo_actuator_palm_mesh_v1-55.STL"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
        <material name="${side}_palm-11_color">
          <color rgba="0.796078 0.823529 0.937255 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://velo_description/meshes/velo_actuator_palm_mesh_v1-55.STL"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
        <origin rpy="0 0 0" xyz="0 0.00 0.0"/>
      </inertial>
    </link>

    <joint name="${side}_gripper_palm_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${side}_gripper_palm_link"/>
      <insert_block name="origin" />
    </joint>

    <link name="${side}_gripper_l_finger_link">
      <visual>
        <geometry>
          <mesh filename="package://velo_description/meshes/velo_proximal_mesh_v1-55.STL"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <material name="${side}_l_finger-11_color">
          <color rgba="0.0 1.0 0.0 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://velo_description/meshes/velo_proximal_mesh_v1-55.STL"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
        <origin rpy="0 0 0" xyz="0 0.00 0.0"/>
      </inertial>
    </link>

    <joint name="${side}_gripper_l_finger_joint" type="continuous">
      <parent link="${side}_gripper_palm_link"/>
      <child link="${side}_gripper_l_finger_link"/>
      <origin rpy="0 0 -${M_PI/2.0}" xyz="0 -0.01750 0.0"/>
<!--
     <limit effort="300.0" velocity = "10000" lower = "0" upper = "${gripper_max_angle}"/>
      <safety_controller k_position="100" k_velocity="1" soft_lower_limit = "0" soft_upper_limit = "1.4224433403753787"/>
-->
      <axis xyz="0 0 1"/>
      <dynamics damping="0.01"/>
    </joint>

    <link name="${side}_gripper_l_finger_tip_link">
      <visual>
        <geometry>
          <mesh filename="package://velo_description/meshes/velo_distal_mesh_v1-55.STL"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <material name="${side}_l_finger_tip-11_color">
          <color rgba="0.796078 0.823529 0.937255 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://velo_description/meshes/velo_distal_mesh_v1-55.STL"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        <origin rpy="0 0 0" xyz="0 0.00 0.0"/>
      </inertial>
    </link>

    <joint name="${side}_gripper_l_finger_tip_joint" type="continuous">
      <parent link="${side}_gripper_l_finger_link"/>
      <child link="${side}_gripper_l_finger_tip_link"/>
      <mimic joint="${side}_gripper_l_finger_joint" multiplier="-1" offset="0"/>
      <origin rpy="0 0 ${M_PI/2.0}" xyz="0.060 0 0"/>
<!--
      <limit effort="300.0" velocity = "10000" lower = "${-gripper_max_angle}" upper = "${gripper_max_angle}"/>
      <safety_controller k_position="100" k_velocity="1" soft_lower_limit = "0" soft_upper_limit = "1.4224433403753787"/>
-->
      <axis xyz="0 0 1"/>
      <dynamics damping="0.01"/>
    </joint>

    <link name="${side}_gripper_r_finger_link">
      <visual>
        <geometry>
          <mesh filename="package://velo_description/meshes/velo_proximal_mesh_v1-55.STL"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <material name="${side}_gripper_r_finger-11_color">
          <color rgba="1.0 0.0 0.0 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://velo_description/meshes/velo_proximal_mesh_v1-55.STL"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        <origin rpy="0 0 0" xyz="0 0.00 0.0"/>
      </inertial>
    </link>

    <joint name="${side}_gripper_r_finger_joint" type="continuous">
      <parent link="${side}_gripper_palm_link"/>
      <child link="${side}_gripper_r_finger_link"/>
      <mimic joint="${side}_gripper_l_finger_joint" multiplier="1" offset="0"/>
      <origin rpy="0 ${M_PI} -${M_PI/2.0}" xyz="0 0.0175 0"/>
<!--
     <limit effort="300.0" velocity = "10000" lower = "${-gripper_max_angle}" upper = "${gripper_max_angle}"/>
      <safety_controller k_position="100" k_velocity="1" soft_lower_limit = "0" soft_upper_limit = "1.4224433403753787"/>
-->
      <axis xyz="0 0 1"/>
      <dynamics damping="0.01"/>
    </joint>

    <link name="${side}_gripper_r_finger_tip_link">
      <visual>
        <geometry>
          <mesh filename="package://velo_description/meshes/velo_distal_mesh_v1-55.STL"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <material name="${side}_r_finger_tip-11_color">
          <color rgba="0.796078 0.823529 0.937255 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://velo_description/meshes/velo_distal_mesh_v1-55.STL"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        <origin rpy="0 0 0" xyz="0 0.00 0.0"/>
      </inertial>
    </link>

    <joint name="${side}_gripper_r_finger_tip_joint" type="continuous">
      <parent link="${side}_gripper_r_finger_link"/>
      <child link="${side}_gripper_r_finger_tip_link"/>
      <mimic joint="${side}_gripper_l_finger_joint" multiplier="-1" offset="0"/>
      <origin rpy="0 0 ${M_PI/2.0}" xyz="0.060 0 0"/>
<!--
      <limit effort="300.0" velocity = "10000" lower = "${-gripper_max_angle}" upper = "${gripper_max_angle}"/>
      <safety_controller k_position="100" k_velocity="1" soft_lower_limit = "0" soft_upper_limit = "1.4224433403753787"/>
-->
      <dynamics damping="0.01"/>
    </joint>

    <link name="${side}_gripper_l_finger_tip_frame"/>

    <link name="${side}_gripper_tool_frame">
      <!--<visual>
        <geometry>
          <sphere radius="0.003"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <material name="${side}_tool_frame-11_color">
          <color rgba="0.796078 0.823529 0.937255 1"/>
        </material>
      </visual>-->
      <inertial>
        <mass value="0.1"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        <origin rpy="0 0 0" xyz="0 0.00 0.0"/>
      </inertial>
    </link>

    <joint name="${side}_gripper_tool_joint" type="fixed">
      <parent link="${side}_gripper_palm_link"/>
      <child link="${side}_gripper_tool_frame"/>
      <origin rpy="0 0 0" xyz="0.0 0.0 0.1"/>
    </joint>
 
    <!-- actuated motor screw joint -->
    <link name="${side}_gripper_motor_slider_link">
      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia  ixx="0.001" ixy="0.0" ixz="0.0"
                  iyy="0.001" iyz="0.0"
                  izz="0.001" />
      </inertial>
      <!-- for debugging only -->
      <!--<visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.05 0.01 0.05" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.05 0.01 0.05" />
        </geometry>
      </collision>-->
      
    </link>
    
    <gazebo reference="${side}_gripper_motor_slider_link">
      <turnGravityOff>true</turnGravityOff>
    
</gazebo>

    <joint name="${side}_gripper_motor_slider_joint" type="prismatic">
      <origin xyz="0 0 ${lcg_finger_to_finger_tip_x + lcg_palm_to_finger_x + lcg_palm_origin_offset}" rpy="0 0 ${M_PI/2.0}" />
      <axis xyz="1 0 0"/>
      <parent link="${side}_gripper_palm_link"/>
      <child link="${side}_gripper_motor_slider_link"/>
<!--
      <limit effort="1000.0" velocity="0.2" lower="-0.135" upper="0.135" />
-->
    </joint>
    <link name="${side}_gripper_motor_screw_link">
      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia  ixx="0.0001" ixy="0.0" ixz="0.0"
                  iyy="0.0001" iyz="0.0"
                  izz="0.0001" />
      </inertial>
      <!-- for debugging only -->
<!--      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.05 0.01 0.05" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.05 0.01 0.05" />
        </geometry>
      </collision> -->
      
    </link>

    <gazebo reference="${side}_gripper_screw_link">
      <turnGravityOff>true</turnGravityOff>
    </gazebo>

    <joint name="${side}_gripper_motor_screw_joint" type="continuous">
      <origin xyz="0.0 0 0" rpy="0 0 0" />
      <axis xyz="0 1 0"/>
      <parent link="${side}_gripper_motor_slider_link"/>
      <child link="${side}_gripper_motor_screw_link"/>
      <dynamics damping="0.0001" />
    </joint>

    <joint name="${side}_gripper_joint" type="prismatic">
      <parent link="${side}_gripper_r_finger_tip_link"/>
      <child link="${side}_gripper_l_finger_tip_frame"/>
      <axis xyz="0 1 0" />
      <dynamics damping="${gripper_damping}" />

    <limit effort="333.3" lower="-99999.9" upper="99999.9" velocity="9.9"/>
<!--    <safety_controller k_position="1e6" k_velocity="1e6" soft_lower_limit="-99999.1" soft_upper_limit="99999.1"/>
-->
    </joint>


    <xacro:pr2_lcgripper_finger_gazebo_v0 prefix="l" reflect="${reflect}" />
    <xacro:pr2_lcgripper_finger_gazebo_v0 prefix="r" reflect="${reflect}" />

    <xacro:pr2_lcgripper_gazebo_v0 side="${side}" />
    <xacro:pr2_lcgripper_transmission_v0 side="${side}"
      gear_reduction="${15.0}"
      gear_efficiency="${1.0}"
      screw_efficiency="${1.0}"
      screw_lead="${0.00325}"

      j0x="${-0.0350}"
      j0y="${0.0}"
      j1x="${-0.060}"
      j1y="${0.0}"

      p0x="${-0.025}"
      p0y="${0.002}"
      p1x="${-0.045}"
      p1y="${0.004}"
      p2x="${-0.0084}"
      p2y="${0.0023}"
      p3x="${-0.044}"
      p3y="${-0.005}"

      l0="${0.035}"
      l1="${0.060}"
      l2="${0.050}"

      p0_radius="${0.004}"
      j1_radius="${0.0032}"
      thickness="${0.006}"
      theta_open="${20.0}"
      theta_closed="${101.5}"

      l2g_coeffs_0="${-0.00065535931852}"
      l2g_coeffs_1="${10.019957576}"
      l2g_coeffs_2="${799.03010689}"
      l2g_coeffs_3="${-70983.900184}"
      l2g_coeffs_4="${1729405.0628}"

      g2l_coeffs_0="${5.429877018e-05}"
      g2l_coeffs_1="${0.097594704184}"
      g2l_coeffs_2="${-0.46537557155}"
      g2l_coeffs_3="${3.3776098694}"
      g2l_coeffs_4="${-6.6643179571}"

      g2ed_coeffs_0="${0.013021055202}"
      g2ed_coeffs_1="${-0.020767789082}"
      g2ed_coeffs_2="${-0.41359925158}"
      g2ed_coeffs_3="${4.8190129478}"
      g2ed_coeffs_4="${-26.74286852}"
	/>
  </xacro:macro>

</robot>
