cal_l_gripper:
  type: velo_controller/VeloCalibrationController
  joint: l_gripper_joint
  actuator: l_velo_gripper_motor
  velocity:  0.003
  error_max: 0.001
  stopped_velocity_tolerance: 0.0005
  pid:
    p: 360000.0
    d: 36000.0
    i: 50000.0
    i_clamp: 40.0
  other_joints:
    - l_gripper_l_finger_joint
    - l_gripper_l_finger_tip_joint
    - l_gripper_r_finger_joint
    - l_gripper_r_finger_tip_joint

l_gripper_controller:
  type: velo_controller/VeloController
  joint: l_gripper_joint
  pid:
    p: 5000.0
    d: 100.0
    i: 1.0
    i_clamp: 0.0
    filter_coeff: 0.1
    use_v_thresh: 1  # Binary Boolean.
    v_thresh: -0.04  # (m/s) Gap closing speed limit. (-.02 reduces most kinetic windup.)
    position_holding:
      stall_timeout: 1.0 # seconds
      stall_threshold: 0.001 # metres of gap travel
      holding_torque: 5.0 # Newtons of gap force
