joint_limits:
  left_shoulder_pan_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1.17
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  left_elbow_flex_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1.17
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  left_wrist_flex_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1.17
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  left_wrist_roll_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1.17
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  left_gripper_left_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1.17
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  right_shoulder_pan_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1.17
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  right_elbow_flex_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1.17
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  right_wrist_flex_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1.17
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  right_wrist_roll_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1.17
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  right_gripper_left_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1.17
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  torso_lift_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.05
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false