<?xml version="1.0"?>

<robot name="robot"
  xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body" 
  xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
  xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
  xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#slider"
  xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor" 
  xmlns:xacro="http://www.ros.org/wiki/xacro"
>
    <!-- Included URDF Files -->
    <include filename="$(find erratic_description)/urdf/materials.urdf.xacro" />
    <include filename="$(find erratic_description)/urdf/erratic_computer.xacro" />
    <include filename="$(find erratic_description)/urdf/erratic_wheel.xacro" />
    <include filename="$(find prlite_urdf)/prlite_wheel.xacro" />
    <include filename="$(find prlite_urdf)/prlite_torso.xacro" />
    <include filename="$(find prlite_urdf)/prlite_smartarm.xacro" />
    <include filename="$(find prlite_urdf)/hokuyo_urg.xacro" />
    <!-- Properties (Constants) -->
    <property name="M_PI" value="3.14159"/>

    <property name="inch_to_meter" value="0.0254" />
    <property name="base_size_x" value="0.4953" />
    <property name="base_size_y" value="0.508" />
    <property name="base_size_z" value="0.4318" />

    <property name="wheel_radius" value="0.0762" />
    <property name="wheel_length" value="0.02" />
    <property name="wheel_offset_x" value="0.17" />
    <property name="wheel_offset_y" value="0.17" />
    <property name="wheel_offset_z" value="0.17" />
    <property name="caster_width" value="0.00254" />

    <property name="motor_block_x" value="0.1651" />
    <property name="motor_block_y" value="0.1651" />

    <property name="motor_block_z" value="-0.05334" />
    <property name="lin_act_x" value="0" />


        <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin,
             navigation stack depends on this frame -->
        <link name="base_footprint">
            <inertial>
                <mass value="0.0001" />
                <origin xyz="0 0 0" />
                <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                         iyy="0.0001" iyz="0.0"
                         izz="0.0001" />
            </inertial>

            <visual>
                <origin xyz="0 0 ${base_size_z/2 + caster_width}" rpy="0 0 0" />
                <geometry>
                    <box size="0.001 0.001 0.001" />
                </geometry>
                <material name="Green" />
            </visual>

            <collision>
                <origin xyz="0 0 ${base_size_z/2 + caster_width}" rpy="0 0 0" />
                <geometry>
                  <box size="0.001 0.001 0.001" />
                </geometry>
            </collision>
        </link>
        <joint name="base_footprint_joint" type="fixed">
            <!-- NB: While you would think this would make it go up, it is oddly reversed.
                 This moves the joint to 0,0,0 where we want it for rviz, etc. -->
            <origin xyz="0 0 ${base_size_z/2 + caster_width}" rpy="0 0 0" />
            <parent link="base_footprint"/>
            <child link="base_link" />
        </joint>
        <!-- Links and Joints (i.e., the robot) -->
        <link name="base_link">
            <inertial>
                <mass value="20" />
                <!-- origin xyz="${-base_size_x/2} ${-base_size_y/2} ${-base_size_z/2}" / -->
                <origin xyz="0 0 0" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0"
                         izz="1.0" />
            </inertial>

            <visual>
                <origin xyz="0.0 0.0 ${base_size_z/2 + caster_width}" rpy="0 0 0" />
                <geometry>
                    <box size="${base_size_x} ${base_size_y} ${base_size_z}" />
                </geometry>
                <material name="Blue" />
            </visual>

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry>
                    <box size="${base_size_x} ${base_size_y} ${base_size_z}" />
                </geometry>
            </collision>
        </link>

<joint name="wheel_linear_actuator_joint" type="prismatic">
  <axis xyz="1 0 0" />
  <limit lower="0.0" upper="0.1016" effort="10000" velocity=".05"/>
  <origin xyz="0 0 0" rpy="0 0 0"/>
  <parent link="base_link"/>
  <child link="wheel_linear_actuator_link"/>
</joint>


<link name="wheel_linear_actuator_link">
  <visual>
    <axis xyz="0 1 0" />
    <origin xyz="${-6*inch_to_meter} 0 0" rpy="0 1.57 0"/>
    <geometry><box size=".0254 .0254 ${8*inch_to_meter}"/></geometry>
    <material name="Silver1"><color rgba="0 0.9 0.9 1.0"/></material>
  </visual>
</link>

<joint name="fl_linear_actuatuor_joint" type="fixed">
  <parent link="wheel_linear_actuator_link"/>
  <child link="fl_anchor_rod_link"/>
  <origin xyz="${lin_act_x*inch_to_meter} 0 0" rpy="0 0 0"/>
</joint>
<joint name="fr_linear_actuatuor_joint" type="fixed">
  <parent link="wheel_linear_actuator_link"/>
  <child link="fr_anchor_rod_link"/>
  <origin xyz="${lin_act_x*inch_to_meter} 0 0" rpy="0 0 0"/>
</joint>
<joint name="bl_linear_actuatuor_joint" type="fixed">
  <parent link="wheel_linear_actuator_link"/>
  <child link="bl_anchor_rod_link"/>
  <origin xyz="${lin_act_x*inch_to_meter} 0 0" rpy="0 0 0"/>
</joint>
<joint name="br_linear_actuatuor_joint" type="fixed">
  <parent link="wheel_linear_actuator_link"/>
  <child link="br_anchor_rod_link"/>
  <origin xyz="${lin_act_x*inch_to_meter} 0 0" rpy="0 0 0"/>
</joint>



        <xacro:prlite_wheel suffix="fl" parent="base_link" reflect_x="1" reflect_y="1">
        </xacro:prlite_wheel>
        <xacro:prlite_wheel suffix="fr" parent="base_link" reflect_x="1" reflect_y="-1">
        </xacro:prlite_wheel>
        <xacro:prlite_wheel suffix="bl" parent="base_link" reflect_x="-1" reflect_y="1">
        </xacro:prlite_wheel>
        <xacro:prlite_wheel suffix="br" parent="base_link" reflect_x="-1" reflect_y="-1">
        </xacro:prlite_wheel>
        <xacro:prlite_torso>
        </xacro:prlite_torso>
        <xacro:smart_arm parent="left_shoulder_pan_link" side="left" >
        </xacro:smart_arm>
        <xacro:smart_arm parent="right_shoulder_pan_link" side="right" >
        </xacro:smart_arm>
        <xacro:hokuyo_urg name="hokuyo" parent="hokuyo_torso_link" >
        </xacro:hokuyo_urg>

</robot>


