#!/bin/bash
#export ROS_HOSTNAME=localhost
#export ROS_HOSTNAME=prlite-controller
#export ROS_MASTER_URI=http://prlite-controller:11311
#export ROS_IP=192.168.1.14
#export ROS_MASTER_URI=http://192.168.1.14:11311
export ROS_HOSTNAME=localhost
export ROS_MASTER_URI=http://localhost:11311

/opt/ros/electric/stacks/prlite/prlite_teleop/launch/pr2lite_kill
cd /opt/ros/electric/stacks/prlite
roscore &
./pc_485net_raw/src/pc_485net_joints.py &
sleep 5
./net_485net_id_handler/src/id_server.py &
sleep 5
cd pr2lite_arm_navigation/launch
roslaunch pr2lite_dynamixel.launch &
sleep 5
roslaunch pr2lite_realrobot0.launch &
sleep 5
roslaunch pr2lite_realrobot1.launch &
sleep 5
roslaunch pr2lite_realrobot2b.launch
