"""autogenerated by genmsg_py from linact_target.msg. Do not edit."""
import roslib.message
import struct


class linact_target(roslib.message.Message):
  _md5sum = "85c8dc58e389d563542ec70b7cfed283"
  _type = "i2c_net_packets/linact_target"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# set this to 6
uint8 dstaddr

#0 or 1
uint8 which

uint16 min
uint16 max

"""
  __slots__ = ['dstaddr','which','min','max']
  _slot_types = ['uint8','uint8','uint16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       dstaddr,which,min,max
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(linact_target, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.dstaddr is None:
        self.dstaddr = 0
      if self.which is None:
        self.which = 0
      if self.min is None:
        self.min = 0
      if self.max is None:
        self.max = 0
    else:
      self.dstaddr = 0
      self.which = 0
      self.min = 0
      self.max = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_2B2H.pack(_x.dstaddr, _x.which, _x.min, _x.max))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.dstaddr, _x.which, _x.min, _x.max,) = _struct_2B2H.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_2B2H.pack(_x.dstaddr, _x.which, _x.min, _x.max))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.dstaddr, _x.which, _x.min, _x.max,) = _struct_2B2H.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_2B2H = struct.Struct("<2B2H")
