"""autogenerated by genmsg_py from wheel_setpoints.msg. Do not edit."""
import roslib.message
import struct


class wheel_setpoints(roslib.message.Message):
  _md5sum = "8cd29c495d257d268568b4947cbf9a4a"
  _type = "i2c_net_packets/wheel_setpoints"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# wheel controller ID (2 = back, 4 = front)
uint8 dstaddr

# ticks per interval (speed)
# left
int16 s0
# right
int16 s1

"""
  __slots__ = ['dstaddr','s0','s1']
  _slot_types = ['uint8','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       dstaddr,s0,s1
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(wheel_setpoints, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.dstaddr is None:
        self.dstaddr = 0
      if self.s0 is None:
        self.s0 = 0
      if self.s1 is None:
        self.s1 = 0
    else:
      self.dstaddr = 0
      self.s0 = 0
      self.s1 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_B2h.pack(_x.dstaddr, _x.s0, _x.s1))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.dstaddr, _x.s0, _x.s1,) = _struct_B2h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_B2h.pack(_x.dstaddr, _x.s0, _x.s1))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.dstaddr, _x.s0, _x.s1,) = _struct_B2h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_B2h = struct.Struct("<B2h")
