port: /dev/magellan_arm
baud: 115200
rate: 5
sync_write: False
sync_read: False
read_rate: 5
write_rate: 5
joints: {
kinect_pan_controller:{id: 1, max_angle: 150, min_angle: -150, max_speed: 25},
elbow_tilt_controllerR:{id: 3, max_angle: 150, min_angle: -150, max_speed: 25},
finger_left_controllerL:{id: 5, max_angle: 150, min_angle: -150, max_speed: 25},
wrist_rotate_controllerL:{id: 6,max_angle: 150, min_angle: -150, max_speed: 25},
finger_right_controllerL:{id: 7,max_angle: 150, min_angle: -150, max_speed: 25},
elbow_tilt_controllerL: {id: 8, max_angle: 150, min_angle: -150, max_speed: 25},
finger_left_controllerR:{id: 10,max_angle: 150, min_angle: -150, max_speed: 25},
wrist_tilt_controllerL:{id: 11, max_angle: 150, min_angle: -150, max_speed: 25},
laser_tilt_controller:{id: 12, max_angle: 150, min_angle: -150, max_speed: 25},
wrist_tilt_controllerR:{id: 14, max_angle: 150, min_angle: -150, max_speed: 25},
finger_right_controllerR:{id: 15,max_angle: 150,min_angle: -150, max_speed: 25},
wrist_rotate_controllerR:{id: 18,max_angle: 150,min_angle: -150, max_speed: 25},
elbow_pan_controllerR:{id: 19, max_angle: 150, min_angle: -150, max_speed: 25},
elbow_pan_controllerL: {id: 21, max_angle: 150, min_angle: -150, max_speed: 25},
kinect_tilt_controller:{id: 23, max_angle: 150, min_angle: -150, max_speed: 25},
shoulder_pan_controllerL: {id: 2, max_angle: 150, min_angle: -150, max_speed: 25},
shoulder_pan_controllerR:{id: 17, max_angle: 150, min_angle: -150, max_speed: 25}
}

dynamixels: {
kinect_pan_controller:{id: 1, max_angle: 150, min_angle: -150, max_speed: 25},
elbow_tilt_controllerR:{id: 3, max_angle: 150, min_angle: -150, max_speed: 25},
finger_left_controllerL:{id: 5, max_angle: 150, min_angle: -150, max_speed: 25},
wrist_rotate_controllerL:{id: 6,max_angle: 150, min_angle: -150, max_speed: 25},
finger_right_controllerL:{id: 7,max_angle: 150, min_angle: -150, max_speed: 25},
elbow_tilt_controllerL: {id: 8, max_angle: 150, min_angle: -150, max_speed: 25},
finger_left_controllerR:{id: 10,max_angle: 150, min_angle: -150, max_speed: 25},
wrist_tilt_controllerL:{id: 11, max_angle: 150, min_angle: -150, max_speed: 25},
laser_tilt_controller:{id: 12, max_angle: 150, min_angle: -150, max_speed: 25},
wrist_tilt_controllerR:{id: 14, max_angle: 150, min_angle: -150, max_speed: 25},
finger_right_controllerR:{id: 15,max_angle: 150,min_angle: -150, max_speed: 25},
wrist_rotate_controllerR:{id: 18,max_angle: 150,min_angle: -150, max_speed: 25},
elbow_pan_controllerR:{id: 19, max_angle: 150, min_angle: -150, max_speed: 25},
elbow_pan_controllerL: {id: 21, max_angle: 150, min_angle: -150, max_speed: 25},
kinect_tilt_controller:{id: 23, max_angle: 150, min_angle: -150, max_speed: 25},
shoulder_pan_controllerL: {id: 2, max_angle: 150, min_angle: -150, max_speed: 25},
shoulder_pan_controllerR:{id: 17, max_angle: 150, min_angle: -150, max_speed: 25}
}

controllers: {
arm_controller: {type: follow_controller, joints: [shoulder_pan_controllerL,elbow_pan_controllerL, elbow_tilt_controllerL, wrist_tilt_controllerL,wrist_rotate_controllerL], onboard: False },
arm_controllerR: {type: follow_controller, joints: [shoulder_pan_controllerR,elbow_tilt_controllerR, elbow_pan_controllerR, wrist_tilt_controllerR, wrist_rotate_controllerR, finger_right_controllerR, finger_left_controllerR] , onboard: False },
head_controller: {type: follow_controller, joints: [kinect_tilt_controller,kinect_pan_controller, laser_tilt_controller], onboard: False }
}

