port: /dev/magellan-i2c-serial
baud: 115200
rate: 5
sync_write: False
sync_read: False
read_rate: 5
write_rate: 5
joints: {
left_shoulder_tilt_joint: {id: 24, max_angle: 150, min_angle: -150, max_speed: 25},
right_shoulder_tilt_joint:{id: 25, max_angle: 150, min_angle: -150, max_speed: 25}
}

dynamixels: {
left_shoulder_tilt_joint: {id: 24, max_angle: 150, min_angle: -150, max_speed: 25},
right_shoulder_tilt_joint:{id: 25, max_angle: 150, min_angle: -150, max_speed: 25}
}

controllers: {
shoulder_controller: {type: follow_controller, joints: [ left_shoulder_tilt_joint, right_shoulder_tilt_joint ], onboard: False },
}

