pub_rate: 1.0 # Optional
base_path: '' # Optional, prepended to all diagnostic output
analyzers:
  joints:
    type: GenericAnalyzer
    path: 'Joints'
    timeout: 5.0
    contains: ['controller','joint']
