planner_configs:
  SBLkConfig1:
    type: kinematic::SBL
  LBKPIECEkConfig1:
    type: kinematic::LBKPIECE
groups:
  - left_arm
  - left_arm_cartesian
  - left_gripper
  - right_arm
  - right_arm_cartesian
  - right_gripper
  - torso
  - torso_cartesian
left_arm:
  planner_type: JointPlanner
  planner_configs:
    - SBLkConfig1
    - LBKPIECEkConfig1
  projection_evaluator: joint_state
left_gripper:
  planner_type: JointPlanner
  planner_configs:
    - SBLkConfig1
    - LBKPIECEkConfig1
  projection_evaluator: joint_state
right_arm:
  planner_type: JointPlanner
  planner_configs:
    - SBLkConfig1
    - LBKPIECEkConfig1
  projection_evaluator: joint_state
right_gripper:
  planner_type: JointPlanner
  planner_configs:
    - SBLkConfig1
    - LBKPIECEkConfig1
  projection_evaluator: joint_state
torso:
  planner_type: JointPlanner
  planner_configs:
    - SBLkConfig1
    - LBKPIECEkConfig1
  projection_evaluator: joint_state
left_arm_cartesian:
  parent_frame: left_arm_shelf_link
  physical_group: left_arm
  planner_type: RPYIKTaskSpacePlanner
  state_spaces:
    - x
    - y
    - z
    - roll
    - pitch
    - yaw
  x:
    type: Linear
    min: -2.0
    max: 2.0
  y:
    type: Linear
    min: -2.0
    max: 2.0
  z:
    type: Linear
    min: -2.0
    max: 2.0
  roll:
    type: Revolute
  pitch:
    type: Revolute
  yaw:
    type: Revolute
  planner_configs:
    - SBLkConfig1
    - LBKPIECEkConfig1
  kinematics_solver: arm_kinematics_constraint_aware/KDLArmKinematicsPlugin
  tip_name: left_gripper_right_link
  root_name: left_arm_shelf_link
  projection_evaluator: joint_state
  longest_valid_segment_fraction: 0.001
right_arm_cartesian:
  parent_frame: right_arm_shelf_link
  physical_group: right_arm
  planner_type: RPYIKTaskSpacePlanner
  state_spaces:
    - x
    - y
    - z
    - roll
    - pitch
    - yaw
  x:
    type: Linear
    min: -2.0
    max: 2.0
  y:
    type: Linear
    min: -2.0
    max: 2.0
  z:
    type: Linear
    min: -2.0
    max: 2.0
  roll:
    type: Revolute
  pitch:
    type: Revolute
  yaw:
    type: Revolute
  planner_configs:
    - SBLkConfig1
    - LBKPIECEkConfig1
  kinematics_solver: arm_kinematics_constraint_aware/KDLArmKinematicsPlugin
  tip_name: right_gripper_left_link
  root_name: right_arm_shelf_link
  projection_evaluator: joint_state
  longest_valid_segment_fraction: 0.001
torso_cartesian:
  parent_frame: torso_lift_link
  physical_group: torso
  planner_type: RPYIKTaskSpacePlanner
  state_spaces:
    - x
    - y
    - z
    - roll
    - pitch
    - yaw
  x:
    type: Linear
    min: -2.0
    max: 2.0
  y:
    type: Linear
    min: -2.0
    max: 2.0
  z:
    type: Linear
    min: -2.0
    max: 2.0
  roll:
    type: Revolute
  pitch:
    type: Revolute
  yaw:
    type: Revolute
  planner_configs:
    - SBLkConfig1
    - LBKPIECEkConfig1
  kinematics_solver: arm_kinematics_constraint_aware/KDLArmKinematicsPlugin
  tip_name: torso_link
  root_name: torso_lift_link
  projection_evaluator: joint_state
  longest_valid_segment_fraction: 0.001