r_gripper_controller:
  type: velo_controller/VeloController
  joint: r_gripper_joint
  pid: 
    p: 10000.0
    d: 425.0
    i: 1.0
    i_clamp: 0.0
    filter_coeff: 0.1
    use_v_thresh: 1  # Binary Boolean.
    v_thresh: -0.04  # (m/s) Gap closing speed limit. (-.02 reduces most kinetic windup.)
    position_holding:
      stall_timeout: 1.0 # seconds
      stall_threshold: 0.001 # metres of gap travel
      holding_torque: 5.0 # Newtons of gap force
l_gripper_controller:
  type: velo_controller/VeloController
  joint: l_gripper_joint
  pid:
    p: 10000.0
    d: 425.0
    i: 1.0
    i_clamp: 0.0
    filter_coeff: 0.1
    use_v_thresh: 1  # Binary Boolean.
    v_thresh: -0.04  # (m/s) Gap closing speed limit. (-.02 reduces most kinetic windup.)
    position_holding:
      stall_timeout: 1.0 # seconds
      stall_threshold: 0.001 # metres of gap travel
      holding_torque: 5.0 # Newtons of gap force
