<?xml version="1.0"?>

<robot name="pr2lite"
  xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
  xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
  xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
  xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#slider"
  xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
  xmlns:xacro="http://www.ros.org/wiki/xacro"
>
    <!-- Included URDF Files -->
    <!-- 
     From Matthew:
      width of outer torso: 0.526999 meters
      height of outer torso: 0.771906 meters
      width of joints of arms: 0.4126992 meters
      joints of arms: 0.05715
    -->
    <include filename="$(find erratic_description)/urdf/materials.urdf.xacro" />
    <include filename="$(find erratic_description)/urdf/erratic_computer.xacro" />
    <include filename="$(find erratic_description)/urdf/erratic_wheel.xacro" />
    <include filename="$(find pr2lite_urdf)/config/pr2lite_wheel.xacro" />
<!--
    <include filename="$(find pr2lite_urdf)/config/pr2lite_torso.xacro" />
-->
    <include filename="$(find pr2lite_urdf)/config/pr2lite_smartarm.xacro" />
    <include filename="$(find pr2lite_urdf)/config/hokuyo_urg.xacro" />
    <!-- Properties (Constants) -->
    <property name="M_PI" value="3.14159"/>

    <property name="inch_to_meter" value="0.0254" />
    <property name="base_size_x" value="0.508" />
    <property name="base_size_y" value="0.508" />
    <property name="base_size_z" value="0.0127" />

    <property name="inner_torso_bottom_size_x" value="0.307" />
    <property name="inner_torso_bottom_size_y" value="0.48" />
    <property name="inner_torso_bottom_size_z" value="0.3" />

    <property name="inner_torso_top_size_x" value="0.17" />
    <property name="inner_torso_top_size_y" value="0.4953" />
    <property name="inner_torso_top_size_z" value="0.46" />

    <property name="wheel_radius" value="0.0762" />
    <property name="wheel_length" value="0.02" />
    <property name="wheel_offset_x" value="0.17" />
    <property name="wheel_offset_y" value="0.17" />
    <property name="wheel_offset_z" value="0.17" />
    <property name="caster_width" value="0.00254" />

    <property name="motor_block_x" value="0.1651" />
    <property name="motor_block_y" value="0.1651" />

    <property name="motor_block_z" value="-0.05334" />
    <property name="lin_act_x" value="0" />
    <property name="z1" value="0.21844" />
    <property name="shelf_width" value="0.00635" />


        <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin, navigation stack depends on this frame -->
        <link name="base_footprint">
            <visual>
	        <origin xyz="0.0 0.0 ${base_size_z/2 + caster_width}" rpy="0 0 0" />
                <geometry>
                    <box size="0.001 0.001 0.001" />
                </geometry>
                <material name="Green" />
            </visual>

            <collision>
                <origin xyz="0.0 0.0 ${base_size_z/2 + caster_width}" rpy="0 0 0" />
                <geometry>
                  <box size="0.001 0.001 0.001" />
                </geometry>
            </collision>
        </link>
        <joint name="base_footprint_joint" type="fixed">
        <!-- NB: While you would think this would make it go up, it is oddly reversed.
              This moves the joint to 0,0,0 where we want it for rviz, etc. -->
            <origin xyz="0.0 0.0 ${base_size_z/2 + caster_width + 10*inch_to_meter}" rpy="0 0 0" />
            <parent link="base_footprint"/>
            <child link="base_link" />
        </joint>
        <!-- Links and Joints (i.e., the robot) -->
        <link name="base_link">
            <inertial>
                <mass value="20" />
                <origin xyz="0 0 ${base_size_z+caster_width + 1*inch_to_meter}" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0"
                         izz="1.0" />
            </inertial>

            <visual>
                <origin xyz="0 0 ${base_size_z/2+caster_width}" rpy="0 0 0" />
                <geometry>
                    <box size="${base_size_x} ${base_size_y} ${base_size_z}" />
                </geometry>
                <material name="Blue" />
            </visual>

            <collision>
                <origin xyz="0 0 ${base_size_z/2+caster_width}" rpy="0 0 0" />
                <geometry>
                    <box size="${base_size_x} ${base_size_y} ${base_size_z}" />
                </geometry>
            </collision>
        </link>

        <joint name="base_inner_torso_joint" type="fixed">
            <origin xyz="${inner_torso_bottom_size_x/2-base_size_x/2} 0.0 ${inner_torso_bottom_size_z/2+base_size_z}"/>
            <parent link="base_link"/>
            <child link="inner_torso_bottom_link" />
        </joint>

        <link name="inner_torso_bottom_link">
            <inertial>
                <mass value="0" />
                <origin xyz="0.0 0.0 0.0" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0"
                         izz="1.0" />
            </inertial>

            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry>
                    <box size="${inner_torso_bottom_size_x} ${inner_torso_bottom_size_y} ${inner_torso_bottom_size_z}" />
                </geometry>
                <material name="Blue" />
            </visual>

            <collision>
                <origin xyz="${-1*inner_torso_bottom_size_x/2} 0.0 0.0" rpy="0 0 0" />
                <geometry>
                    <box size="${inner_torso_bottom_size_x} ${inner_torso_bottom_size_y} ${inner_torso_bottom_size_z}" />
                </geometry>
            </collision>
        </link>


        <!-- 6.85in x 19 x 17.9 -->
        <joint name="inner_torso_top_joint" type="fixed">
            <origin xyz="${-inner_torso_bottom_size_x/2 + inner_torso_top_size_x/2} 0.0 0.0" rpy="0 0 0" />
            <parent link="inner_torso_bottom_link"/>
            <child link="inner_torso_top_link" />
        </joint>

        <link name="inner_torso_top_link">
            <inertial>
                <mass value="0" />
                <origin xyz="${-inner_torso_top_size_x/2 + inner_torso_top_size_x/2} 0.0 0.0" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0"
                         izz="1.0" />
            </inertial>

            <visual>
                <origin xyz="${-inner_torso_top_size_x/2 + inner_torso_top_size_x/2} 0.0 ${inner_torso_bottom_size_z}" rpy="0 0 0" />
                <geometry>
                    <box size="${inner_torso_top_size_x} ${inner_torso_top_size_y} ${inner_torso_top_size_z}" />
                </geometry>
                <material name="Blue" />
            </visual>

            <collision>
                <origin xyz="${-inner_torso_top_size_x/2} 0.0 ${inner_torso_bottom_size_z}" rpy="0 0 0" />
                <geometry>
                    <box size="${inner_torso_top_size_x} ${inner_torso_top_size_y} ${inner_torso_top_size_z}" />
                </geometry>
            </collision>
        </link>
<joint name="torso_body_joint" type="fixed">
  <parent link="inner_torso_bottom_link"/>
  <child link="torso_lift_link"/>
 <origin xyz="${inch_to_meter*12.35/2} 0 ${inch_to_meter*6.5}" rpy="0 0 0"/>
</joint>
<link name="torso_lift_link">
            <inertial>
                <mass value="0" />
                <origin xyz="0.0 0.0 0.0" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0"
                         izz="1.0" />
            </inertial>
  <visual>
    <axis xyz="0 0 0" />
    <origin xyz="${inch_to_meter*0} ${inch_to_meter*0} ${inch_to_meter*-1.5}" rpy="0 0 0"/>
    <geometry><box size="${inch_to_meter*1} ${inch_to_meter*1} ${inch_to_meter*17}"/></geometry>
    <material name="Silver1"><color rgba="0 0.9 0.9 1.0"/></material>
  </visual>
</link>
<joint name="torso_lift_joint" type="prismatic">
  <axis xyz="0 0 1" />
  <limit lower="0.0" upper="${inch_to_meter*12}" effort="10000" velocity=".05"/>
  <origin xyz="-0 0 0" rpy="0 0 0"/>
  <parent link="torso_lift_link"/>
  <child link="torso_link"/>
  <origin xyz="0 ${inch_to_meter*0.5} 0" rpy="0 0 0"/>
</joint>
<link name="torso_link">
           <inertial>
                <mass value="0" />
                <origin xyz="0.0 0.0 0.0" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0"
                         izz="1.0" />
            </inertial>

  <visual>
    <axis xyz="0 0 0" />
    <origin xyz="${inch_to_meter*(.5)} ${inch_to_meter*0} ${inch_to_meter*2.5}" rpy="0 0 0"/>
    <geometry><box size="${inch_to_meter*.25} .1587 ${inch_to_meter*24.39}"/></geometry>
    <material name="Silver1"><color rgba="0 0.9 0.9 1.0"/></material>
  </visual>
</link>
<joint name="torso_body_joint2" type="fixed">
  <parent link="torso_link"/>
  <child link="bottom_outer_torso_link"/>
 <origin xyz="0 0 ${-inch_to_meter*6}" rpy="0 0 0"/>
</joint>
<link name="bottom_outer_torso_link">
            <inertial>
                <mass value="0" />
                <origin xyz="0.0 0.0 0.0" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0"
                         izz="1.0" />
            </inertial>

  <visual>
    <axis xyz="0 0 0" />
    <origin xyz="${inch_to_meter*(.5)} ${inch_to_meter*0} ${inch_to_meter*0}" rpy="0 0 0"/>
    <geometry><box size="${inch_to_meter*.25} ${inch_to_meter*20.75} ${inch_to_meter*12.75}"/></geometry>
    <material name="Silver1"><color rgba="0 0.9 0.9 1.0"/></material>
  </visual>
</link>
<joint name="top_shelf_joint" type="fixed">
  <parent link="bottom_outer_torso_link"/>
  <child link="top_shelf_link"/>
  <origin xyz="0 ${shelf_width} ${inch_to_meter*5}" rpy="0 0 0"/>
</joint>
<link name="top_shelf_link">
            <inertial>
                <mass value="0" />
                <origin xyz="0.0 0.0 0.0" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0"
                         izz="1.0" />
            </inertial>

  <visual>
    <origin xyz="${-inch_to_meter*2.5} ${inch_to_meter*0} ${inch_to_meter*30.5/2}" rpy="0 0 0"/>
    <geometry><box size="${inch_to_meter*6} ${inch_to_meter*20} ${inch_to_meter*.25}"/></geometry>
    <material name="Grey1"><color rgba="0 0.9 0.9 1.0"/></material>
  </visual>
</link>
<!-- PR2LITE HEAD starts here -->


<joint name="neck_joint" type="fixed">
  <parent link="top_shelf_link"/>
  <child link="neck_link"/>
  <origin xyz="${inch_to_meter*(-3+(.25/2))} ${inch_to_meter*0} ${inch_to_meter*(15.25)}" rpy="0 0 0"/>
</joint>
<link name="neck_link">
            <inertial>
                <mass value="0" />
                <origin xyz="0.0 0.0 0.0" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0"
                         izz="1.0" />
            </inertial>

  <visual>
    <origin xyz="${inch_to_meter*0} ${inch_to_meter*0} ${inch_to_meter*6.5/2}" rpy="0 0 0"/>
    <geometry><box size="${inch_to_meter*-.25} ${inch_to_meter*5.75} ${inch_to_meter*6.5}"/></geometry>
    <material name="Brown"><color rgba="0 0.9 0.9 1.0"/></material>
  </visual>
</link>
<joint name="top_neck_joint" type="fixed">
  <parent link="neck_link"/>
  <child link="top_neck_link"/>
  <origin xyz="${inch_to_meter*0} ${inch_to_meter*0} ${inch_to_meter*(6.5)}" rpy="0 0 0"/>
</joint>
<link name="top_neck_link">
            <inertial>
                <mass value="0" />
                <origin xyz="0.0 0.0 0.0" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0"
                         izz="1.0" />
            </inertial>

  <visual>
    <origin xyz="${inch_to_meter*2} ${inch_to_meter*0} ${inch_to_meter*.25/2}" rpy="0 0 0"/>
    <geometry><box size="${inch_to_meter*4} ${inch_to_meter*5.75} ${inch_to_meter*.25}"/></geometry>
    <material name="Silver1"><color rgba="0 0.9 0.9 1.0"/></material>
  </visual>
</link>

<!-- 4x 13.14 -->
<joint name="head_pan_joint" type="revolute">
  <limit effort="10" lower="-3.1416" upper="3.1416" velocity="3"/>
  <parent link="top_neck_link"/>
  <child link="head_pan_link"/>
  <origin xyz="${inch_to_meter*2} ${inch_to_meter*(0)} ${inch_to_meter*(.25+.125)}" rpy="0 0 0"/>
  <axis xyz="0 0 1"/>
</joint>

<link name="head_pan_link">
            <inertial>
                <mass value="0" />
                <origin xyz="0.0 0.0 0.0" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0"
                         izz="1.0" />
            </inertial>

  <visual>
    <origin xyz="${inch_to_meter*0} ${inch_to_meter*0} ${inch_to_meter*0}" rpy="0 0 0"/>
    <geometry><box size="${inch_to_meter*4} ${inch_to_meter*13.14} ${inch_to_meter*.25}"/></geometry>
    <material name="Silver1"><color rgba="0 0.9 0.9 1.0"/></material>
  </visual>
</link>

<joint name="head_side_joint" type="fixed">
  <parent link="head_pan_link"/>
  <child link="head_side_link"/>
  <origin xyz="${inch_to_meter*0} ${inch_to_meter*((13.14/2)-(.25/2))} ${inch_to_meter*(2.5)}" rpy="0 0 0"/>
</joint>

<link name="head_side_link">
            <inertial>
                <mass value="0" />
                <origin xyz="0.0 0.0 0.0" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0"
                         izz="1.0" />
            </inertial>

  <visual>
    <origin xyz="${inch_to_meter*0} ${inch_to_meter*(-.25/2)} ${inch_to_meter*0}" rpy="0 0 0"/>
    <geometry><box size="${inch_to_meter*4} ${inch_to_meter*.25} ${inch_to_meter*5}"/></geometry>
    <material name="Silver1"><color rgba="0 0.9 0.9 1.0"/></material>
  </visual>
</link>
<joint name="head_tilt_joint" type="revolute">
  <limit effort="10" lower="-3.1416" upper="3.1416" velocity="3"/>
  <parent link="head_side_link"/>
  <child link="kinect_side_link"/>
  <origin xyz="${inch_to_meter*0} ${inch_to_meter*(-.25)} ${inch_to_meter*.5}" rpy="0 0 0"/>
  <axis xyz="0 1 0"/>
</joint>

<link name="kinect_side_link">
            <inertial>
                <mass value="0" />
                <origin xyz="0.0 0.0 0.0" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0"
                         izz="1.0" />
            </inertial>

  <visual>
    <origin xyz="${inch_to_meter*0} ${inch_to_meter*(-.25/2)} ${inch_to_meter*0}" rpy="0 0 0"/>
    <geometry><box size="${inch_to_meter*(4)} ${inch_to_meter*-.25} ${inch_to_meter*(4)}"/></geometry>
    <material name="green"><color rgba="0 0.9 0.9 1.0"/></material>
  </visual>
</link>

<joint name="kinect_side_joint" type="fixed">
  <parent link="kinect_side_link"/>
  <child link="kinect_base_link"/>
  <origin xyz="${inch_to_meter*-(0)} ${inch_to_meter*(0)} ${inch_to_meter*-(2.04+(.25/2))}" rpy="0 0 0"/>
</joint>

<link name="kinect_base_link">
            <inertial>
                <mass value="0" />
                <origin xyz="0.0 0.0 0.0" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0"
                         izz="1.0" />
           </inertial>

  <visual>
    <origin xyz="${inch_to_meter*0} ${inch_to_meter*(-11.5/2)} ${inch_to_meter*0}" rpy="0 0 0"/>
    <geometry><box size="${inch_to_meter*4} ${inch_to_meter*11.5} ${inch_to_meter*-.25}"/></geometry>
    <material name="Green"><color rgba="0 0.9 0.9 1.0"/></material>
  </visual>
</link>

<!-- KINECT STANDOFF -->
<property name="M_SCALE" value="0.001"/>
    <joint name="standoff1_kinect_joint" type="fixed">
      <origin xyz="${inch_to_meter*11/16} ${inch_to_meter*-1.75} ${inch_to_meter*0}" rpy="0 0 0" />
      <parent link="kinect_base_link" />
      <child link="standoff1_kinect_link" />
    </joint>
    <link name="standoff1_kinect_link">
      <inertial>
        <mass value="0.001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0"
          izz="0.0001" />
      </inertial>
      <visual>
        <origin xyz=" 0 0 0 " rpy="0 0 0" />
        <geometry>
          <mesh filename="package://pr2lite_urdf/config/meshes/68-04556-RA_Kinect_Standoff_Assy.3ds" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
          <cylinder length="0.008585" radius="0.001111"/>
        </geometry>
      </collision>
    </link>

    <joint name="standoff2_kinect_joint" type="fixed">
      <origin xyz="${inch_to_meter*11/16} ${inch_to_meter*(-1.75-7.75)} ${inch_to_meter*0}" rpy="0 0 0" />
      <parent link="kinect_base_link" />
      <child link="standoff2_kinect_link" />
    </joint>
    <link name="standoff2_kinect_link">
      <inertial>
        <mass value="0.001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0"
          izz="0.0001" />
      </inertial>
      <visual>
        <origin xyz=" 0 0 0 " rpy="0 0 0" />
        <geometry>
          <mesh filename="package://pr2lite_urdf/config/meshes/68-04556-RA_Kinect_Standoff_Assy.3ds" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
          <cylinder length="0.008585" radius="0.001111"/>
        </geometry>
      </collision>
    </link>

<!-- KINECT SENSOR -->
<joint name="base_kinect_joint" type="fixed">
<!--
      <origin xyz="-0.0844382 0 0.1047496" rpy="0 0 0" />
    <origin xyz="${inch_to_meter*11/16} ${inch_to_meter*(-11.5/2)} ${0.1047496}" rpy="0 0 0"/>
-->
    <origin xyz="${inch_to_meter*(1+3/8)} ${inch_to_meter*(-11.5/2)} ${0.1047496}" rpy="0 0 0"/>
      <parent link="kinect_base_link" />
      <child link="kinect_link" />
    </joint>
    <link name="kinect_link">
      <inertial>
        <mass value="12" />
        <origin xyz="0 0 0" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                 iyy="1.0" iyz="0.0"
                 izz="1.0" />
      </inertial>
      <visual>
        <origin xyz=" 0 0 0 " rpy="0 0 0" />
        <geometry>
          <mesh filename="package://pr2lite_urdf/config/meshes/68-04546_Kinect_Sensor.3ds" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://pr2lite_urdf/config/meshes/68-04546_Kinect_Sensor.3ds"/>
          </geometry>
      </collision>
    </link>
    <joint name="kinect_depth_joint" type="fixed">
      <origin xyz="0 0.018 0" rpy="0 0 0" />
      <parent link="kinect_link" />
      <child link="kinect_depth_frame" />
    </joint>
   
    <link name="kinect_depth_frame">
      <inertial>
        <mass value="0.0001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                 iyy="0.0001" iyz="0.0"
                 izz="0.0001" />
      </inertial>
    </link>
   
    <joint name="kinect_depth_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="kinect_depth_frame" />
      <child link="kinect_depth_optical_frame" />
    </joint>
   
    <link name="kinect_depth_optical_frame">
      <inertial>
        <mass value="0.0001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                 iyy="0.0001" iyz="0.0"
                 izz="0.0001" />
      </inertial>
    </link>
   
   
    <joint name="kinect_rgb_joint" type="fixed">
      <origin xyz="0 -0.005 0" rpy="0 0 0" />
      <parent link="kinect_link" />
      <child link="kinect_rgb_frame" />
    </joint>
   
    <link name="kinect_rgb_frame">
      <inertial>
        <mass value="0.0001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                 iyy="0.0001" iyz="0.0"
                 izz="0.0001" />
      </inertial>
    </link>
   
    <joint name="kinect_rgb_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="kinect_rgb_frame" />
      <child link="kinect_rgb_optical_frame" />
    </joint>
   
    <link name="kinect_rgb_optical_frame">
      <inertial>
        <mass value="0.0001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                 iyy="0.0001" iyz="0.0"
                 izz="0.0001" />
      </inertial>
    </link>
<!--
standoffs from side 1.858 from front 0.775
hokuyo side bar dimensions: 2.594 jutting out 1"high
hokuyo side bar location: 1.875 + .5 (center) from bottom, 1.274 (+eight inch)  from side
hokuyo rotate .5 from front, .5 from top
hokuyo gap .368 
hokuyo body rotate 1.024 from front, 1.017 from bottom
hokuyo side bar dimensions: 
-->

<joint name="lidar_bar_joint" type="fixed">
  <parent link="neck_link"/>
  <child link="lidar_bar_link"/>
  <origin xyz="${inch_to_meter*0} ${inch_to_meter*(1.273+.25/2)} ${inch_to_meter*(1.87+.5)}" rpy="0 0 0"/>
</joint>

<link name="lidar_bar_link">
            <inertial>
                <mass value="0" />
                <origin xyz="0.0 0.0 0.0" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0"
                         izz="1.0" />
            </inertial>

  <visual>
    <origin xyz="${inch_to_meter*(2.594/2)} ${inch_to_meter*0} ${inch_to_meter*0}" rpy="0 0 0"/>
    <geometry><box size="${inch_to_meter*2.594} ${inch_to_meter*.25} ${inch_to_meter*1}"/></geometry>
    <material name="Silver1"><color rgba="0 0.9 0.9 1.0"/></material>
  </visual>
</link>
<joint name="lidar_tilt_joint" type="revolute">
  <limit effort="10" lower="-3.1416" upper="3.1416" velocity="3"/>
  <parent link="lidar_bar_link"/>
  <child link="lidar_tilt_link"/>
  <origin xyz="${inch_to_meter*2.094} ${inch_to_meter*-.25} ${inch_to_meter*(0)}" rpy="0 0 0"/>
  <axis xyz="0 -1 0"/>
</joint>
<link name="lidar_tilt_link">
            <inertial>
                <mass value="0" />
                <origin xyz="0.0 0.0 0.0" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0"
                         izz="1.0" />
            </inertial>

  <visual>
    <origin xyz="${inch_to_meter*0} ${inch_to_meter*0} ${inch_to_meter*0}" rpy="0 0 0"/>
    <geometry><box size="${inch_to_meter*(2)} ${inch_to_meter*-.25} ${inch_to_meter*2}"/></geometry>
    <material name="Green"><color rgba="0 0.9 0.9 1.0"/></material>
  </visual>
</link>

<joint name="lidar_base_joint" type="fixed">
  <parent link="lidar_tilt_link"/>
  <child link="lidar_base_link"/>
  <origin xyz="${inch_to_meter*0} ${inch_to_meter*-1} ${inch_to_meter*-1}" rpy="0 0 0"/>
</joint>

<link name="lidar_base_link">
            <inertial>
                <mass value="0" />
                <origin xyz="0.0 0.0 0.0" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0"
                         izz="1.0" />
            </inertial>

  <visual>
  <origin xyz="${inch_to_meter*0} ${inch_to_meter*0} ${inch_to_meter*(0)}" rpy="0 0 0"/>
    <geometry><box size="${inch_to_meter*2} ${inch_to_meter*2} ${inch_to_meter*.25}"/></geometry>
    <material name="Green"><color rgba="0 0.9 0.9 1.0"/></material>
  </visual>
</link>

<xacro:hokuyo_urg name="hokuyo_tilt" parent="lidar_base_link" >
</xacro:hokuyo_urg>
<!--
-->


<!-- PR2LITE HEAD ends here -->
<joint name="left_arm_shelf_joint" type="fixed">
<parent link="top_shelf_link"/>
<child link="left_arm_shelf_link"/>
<origin xyz="${inch_to_meter*0} ${inch_to_meter*7} ${inch_to_meter*(15-.19)}" rpy="0 0 0"/>
</joint>

<link name="left_arm_shelf_link">
            <inertial>
                <mass value="0" />
                <origin xyz="0.0 0.0 0.0" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0"
                         izz="1.0" />
            </inertial>

<visual>
<origin xyz="${inch_to_meter*-2.5} ${inch_to_meter*0} ${inch_to_meter*0}" rpy="0 0 0"/>
<geometry><box size="${inch_to_meter*6} ${inch_to_meter*6} ${inch_to_meter*.25}"/></geometry>
<material name="Silver1"><color rgba="0 0.9 0.9 1.0"/></material>
</visual>
</link>
<!--
-->
<joint name="left_arm_base_link" type="fixed">
<axis xyz="0 0 -1" />
<parent link="left_arm_shelf_link"/>
<child link="left_shoulder_pan_link"/>
<origin xyz="${inch_to_meter*-2.5} ${inch_to_meter*0} ${inch_to_meter*0}" rpy="0 3.14 3.14"/>
</joint>
<joint name="right_arm_shelf_joint" type="fixed">
<parent link="top_shelf_link"/>
<child link="right_arm_shelf_link"/>
<origin xyz="${inch_to_meter*0} ${inch_to_meter*-7} ${inch_to_meter*(15-.19)}" rpy="0 0 0"/>
</joint>

<link name="right_arm_shelf_link">
            <inertial>
                <mass value="0" />
                <origin xyz="0.0 0.0 0.0" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0"
                         izz="1.0" />
            </inertial>
<visual>
<axis xyz="0 0 -1" />
<origin xyz="${inch_to_meter*-2.5} ${inch_to_meter*0} ${inch_to_meter*0}" rpy="0 0 0"/>
<geometry><box size="${inch_to_meter*6} ${inch_to_meter*6} ${inch_to_meter*.25}"/></geometry>
<material name="Silver1"><color rgba="0 0.9 0.9 1.0"/></material>
</visual>
</link>

<!--
-->
<joint name="right_arm_base_link" type="fixed">
<parent link="right_arm_shelf_link"/>
<child link="right_shoulder_pan_link"/>
<origin xyz="${inch_to_meter*-2.5} ${inch_to_meter*0} ${inch_to_meter*0}" rpy="0 3.14 3.14"/>
</joint>



<joint name="wheel_linear_actuator_joint" type="prismatic">
<axis xyz="1 0 0" />
<limit lower="0.0" upper="0.1016" effort="10000" velocity=".05"/>
<origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
<parent link="base_link"/>
<child link="wheel_linear_actuator_link"/>
</joint>


<link name="wheel_linear_actuator_link">
            <inertial>
                <mass value="0" />
                <origin xyz="0.0 0.0 0.0" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0"
                         izz="1.0" />
            </inertial>

<visual>
<axis xyz="0 1 0" />
<origin xyz="${-6*inch_to_meter} 0.0 0.0" rpy="0 1.57 0"/>
<geometry><box size=".0254 .0254 ${8*inch_to_meter}"/></geometry>
<material name="Silver1"><color rgba="0.0 0.9 0.9 1.0"/></material>
</visual>
</link>

<joint name="fl_linear_actuatuor_joint" type="fixed">
<parent link="wheel_linear_actuator_link"/>
<child link="fl_anchor_rod_link"/>
<origin xyz="${lin_act_x*inch_to_meter} 0.0 0.0" rpy="0 0 0"/>
</joint>
<joint name="fr_linear_actuatuor_joint" type="fixed">
<parent link="wheel_linear_actuator_link"/>
<child link="fr_anchor_rod_link"/>
<origin xyz="${lin_act_x*inch_to_meter} 0.0 0.0" rpy="0 0 0"/>
</joint>
<joint name="bl_linear_actuatuor_joint" type="fixed">
<parent link="wheel_linear_actuator_link"/>
<child link="bl_anchor_rod_link"/>
<origin xyz="${lin_act_x*inch_to_meter} 0.0 0.0" rpy="0 0 0"/>
</joint>
<joint name="br_linear_actuatuor_joint" type="fixed">
<parent link="wheel_linear_actuator_link"/>
<child link="br_anchor_rod_link"/>
<origin xyz="${lin_act_x*inch_to_meter} 0.0 0.0" rpy="0 0 0"/>
</joint>



<xacro:pr2lite_wheel suffix="fl" parent="base_link" reflect_x="1" reflect_y="1">
</xacro:pr2lite_wheel>
<xacro:pr2lite_wheel suffix="fr" parent="base_link" reflect_x="1" reflect_y="-1">
</xacro:pr2lite_wheel>
<xacro:pr2lite_wheel suffix="bl" parent="base_link" reflect_x="-1" reflect_y="1">
</xacro:pr2lite_wheel>
<xacro:pr2lite_wheel suffix="br" parent="base_link" reflect_x="-1" reflect_y="-1">
</xacro:pr2lite_wheel>
<xacro:pr2lite_torso>
</xacro:pr2lite_torso>
<!--
-->
<xacro:smart_arm parent="left_shoulder_pan_link" side="left" >
</xacro:smart_arm>
<xacro:smart_arm parent="right_shoulder_pan_link" side="right" >
</xacro:smart_arm>


<!-- hokuyu on base -->
<joint name="hokuyo_torso_joint" type="fixed">
<parent link="base_link"/>
<child link="hokuyo_torso_link"/>
<origin xyz="${inch_to_meter*9} 0 ${inch_to_meter*0}" rpy="0 0 0"/>
</joint>

<link name="hokuyo_torso_link">
            <inertial>
                <mass value="0" />
                <origin xyz="0.0 0.0 0.0" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0"
                         izz="1.0" />
            </inertial>

<origin xyz="${inch_to_meter*0} ${inch_to_meter*0} ${inch_to_meter*0}" rpy="0 0 0"/>
</link>

<xacro:hokuyo_urg name="hokuyo" parent="hokuyo_torso_link" >
</xacro:hokuyo_urg>

</robot>




