<?xml version="1.0"?>

<robot
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">
    
    <!-- Properties (Constants) -->
    <property name="M_PI" value="3.14159"/>
    <property name="inch_to_meter" value="0.0254"/>
    <property name="caster_offset_z" value="-0.00635"/>
    <property name="wheel_offset_z" value="${-base_size_z/2 + 0.0236}" />
    <property name="caster_width" value="0.00254"/>
    <property name="caster_link_offset_z" value="0.00635"/>
    <property name="caster_size_x" value="0.1016"/>
    <property name="caster_size_y" value="0.1016"/>
    <property name="caster_size_z" value="0.00635"/>
    <property name="push_rod_x" value="0.0889"/>
    <property name="push_rod_y" value="0.507"/>
    <property name="push_rod_z" value="0"/>
    <property name="push_rod_sz_x" value="0.1778"/>
    <property name="push_rod_sz_y" value="0.01905"/>
    <property name="push_rod_sz_z" value="0.00127"/>
    <property name="anchor_rod_sz_x" value="0.01905"/>
    <property name="anchor_rod_sz_y" value="0.1651"/>
    <property name="anchor_rod_sz_z" value="0.00127"/>
    <property name="push_joint_z" value="0.00635"/>
    <!-- 8 * inch_to_meter
      <property name="base_size_x" value="0.4953" />
      <property name="base_size_y" value="0.508" />
      <property name="base_size_z" value="0.3556" />
    -->
    <property name="motor_block_x" value="0.1651" />
    <property name="motor_block_y" value="0.1651" />
    <property name="motor_block_z" value="-0.05334" />
    <property name="motor_block_size_x" value="0.1016"/>
    <property name="motor_block_size_y" value="0.0254" />
    <property name="motor_block_size_z" value="0.1016"/>
    <property name="wheel_radius" value=".0762"/>

 <macro name="pr2lite_wheel" params="suffix parent reflect_x reflect_y">
<!-- * * * Link Definitions * * * -->
<joint name="${suffix}_base_joint" type="fixed">
  <axis xyz="0 0 1" />
  <parent link="base_link"/>
  <child link="${suffix}_base_link"/>
  <origin xyz="${motor_block_x*reflect_x} ${motor_block_y*reflect_y} ${caster_offset_z}" rpy="0 0 0"/>
</joint>
<link name="${suffix}_base_link">
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry><box size=".0201 .0201 .0001"/></geometry>
    <material name="Grey1"><color rgba="0 0.9 0.9 1.0"/></material>
  </visual>
</link>
<link name="${suffix}_anchor_rod_link">
  <visual>
    <axis xyz="0 0 1" />
    <origin xyz="${-2*inch_to_meter} ${-1*(anchor_rod_sz_y+(reflect_x*reflect_y*caster_size_y/2))/2*reflect_y)} 0" rpy="0 0 0"/>
    <geometry><box size="${anchor_rod_sz_x} ${anchor_rod_sz_y + (reflect_x*reflect_y*caster_size_y/2)} ${anchor_rod_sz_z}"/></geometry>
    <material name="Silver1"><color rgba="0 0.9 0.9 1.0"/></material>
  </visual>
</link>
<joint name="${suffix}_anchor_rod_joint" type="revolute">
  <axis xyz="0 0 1" />
  <limit lower="-3.1416" upper="3.1416" effort="10" velocity="3"/>
  <parent link="${suffix}_anchor_rod_link"/>
  <child link="${suffix}_push_rod_link"/>
  <origin xyz="${-2*inch_to_meter} ${(anchor_rod_sz_y+(reflect_x*caster_size_y/2))*reflect_y)} 0" rpy="0 0 0"/>
</joint>
<link name="${suffix}_push_rod_link">
  <visual>
    <axis xyz="0 0 1" />
    <origin xyz="${push_rod_sz_x/2*reflect_x*(-1)} 0 0" rpy="0 0 0"/>
    <geometry><box size="${push_rod_sz_x} ${push_rod_sz_y} ${push_rod_sz_z}"/></geometry>
    <material name="Silver1"><color rgba="0 0.9 0.9 1.0"/></material>
  </visual>
</link>
<!--
<joint name="${suffix}_push_rod_joint" type="revolute">
  <axis xyz="0 0 1" />
  <limit lower="-3.1416" upper="3.1416" effort="10" velocity="3"/>
  <parent link="${suffix}_push_rod_link"/>
  <child link="${suffix}_caster_link"/>
  <origin xyz="${push_rod_sz_x*reflect_x*(-1)} 0 0" rpy="0 0 0"/>
</joint>
-->
<joint name="${suffix}_caster_rotation_joint" type="revolute">
  <axis xyz="0 0 1" />
  <limit lower="-3.1416" upper="3.1416" effort="10" velocity="3"/>
  <parent link="${suffix}_base_link"/>
  <child link="${suffix}_caster_link"/>
  <origin xyz="0 0 0" rpy="0 0 0"/>
</joint>
<link name="${suffix}_caster_link">
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry><box size="${caster_size_x} ${caster_size_y} ${caster_size_z}"/></geometry>
    <material name="Grey1"><color rgba="0 0.9 0.9 1.0"/></material>
  </visual>
</link>

<joint name="${suffix}_caster_motor_joint" type="fixed">
  <axis xyz="0 0 1" />
  <parent link="${suffix}_caster_link"/>
  <child link="${suffix}_wheel_motor_block_link"/>
  <origin xyz="0 0 0" rpy="0 0 0"/>
</joint>

<link name="${suffix}_wheel_motor_block_link">
  <visual>
    <origin xyz="0 0 ${-motor_block_size_z/2}" rpy="0 0 0"/>
    <geometry><box size="${motor_block_size_x} ${motor_block_size_y} ${motor_block_size_z}"/></geometry>
    <material name="Blue1"><color rgba="0 0.9 0.9 1.0"/></material>
  </visual>
</link>
<joint name="${suffix}_wheel_joint" type="continuous">
      <axis xyz="0 1 0" />
      <limit effort="100" velocity="100"/>
      <safety_controller  k_velocity="10" />
      <dynamics damping="0.0" friction="0.0" />
      <origin xyz="0 ${motor_block_size_y*reflect_y} ${- 1*wheel_radius-(.5*inch_to_meter)}" rpy="0 0 0" />
  <parent link="${suffix}_wheel_motor_block_link"/>
  <child link="${suffix}_wheel_link"/>
</joint>
<link name="${suffix}_wheel_link">
            <inertial>
                <mass value="0.1" />
                <origin xyz=" 0 0 0 " />
                <inertia  ixx="0.012411765597" ixy="0.0" ixz="0.0"
                          iyy="0.015218160428" iyz="0.0"
                          izz="0.011763977943" />
            </inertial>
           <visual>
                <origin xyz="0 ${0.25*inch_to_meter*reflect_y} 0" rpy="0 ${M_PI/2} ${M_PI/2}" />
                <geometry><cylinder radius="${wheel_radius}" length = "${0.5*inch_to_meter}"/></geometry>
                <material name="Grey" />
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 ${M_PI/2} ${M_PI/2}" />
                <geometry><cylinder radius="${wheel_radius}" length = "${inch_to_meter*0.5}"/></geometry>
            </collision>
        <gazebo reference="${parent}_${suffix}_wheel_link" >
            <mu1 value="100.0" />
            <mu2 value="100.0" />
            <kp  value="1000000.0" />
            <kd  value="1.0" />
            <material>Erratic/Grey</material>
        </gazebo>
        <gazebo reference="${parent}_${suffix}_motor_link" >
            <material>Erratic/White</material>
        </gazebo>
        <transmission type="pr2_mechanism_model/SimpleTransmission" name=
"${parent}_${suffix}_wheel_trans">
            <actuator name="${parent}_${suffix}_wheel_motor" />
            <joint name="${parent}_${suffix}_wheel_joint" />
            <mechanicalReduction>1.0</mechanicalReduction>
        </transmission>
</link>



 </macro>

    
</robot>

