pub_rate: 1.0 # Optional
base_path: '' # Optional, prepended to all diagnostic output
analyzers:
  nodes: 
    type: diagnostic_aggregator/GenericAnalyzer
    path: 'Nodes'
    timeout: 5.0
    contains: ['Node']
  power:
    type: diagnostic_aggregator/GenericAnalyzer
    path: 'Power System'
    timeout: 5.0
    startswith: ['Battery', 'Charging Sources', 'Laptop Battery']

